<?php

    echo __('<br/>Here are your XCHANGE products...');

    echo __('<br/><table style="background-color:cyan;" border=1>');

    echo __('<tr><th>Sku#</th><th>Product</th><th>License#/Serial#</th><th>URL</th></tr>');

    echo __('<tr><td>1014-46</td><td>Some product plugin.</td><td>000111-0055369</td><td>www.google.ca/reg</td></tr>');

    echo __('<tr><td>1014-00</td><td>Another great plugin Ver1.</td><td>654-abc-456-777</td><td>www.mmstore.ca/activate</td></tr>');

    echo __('<tr><td>1014-46</td><td>Some product plugin.</td><td>000111-0055369</td><td>www.google.ca/reg</td></tr>');
    echo __('<tr><td>1014-00</td><td>Another great plugin Ver1.</td><td>654-abc-456-777</td><td>www.mmstore.ca/activate</td></tr>');
    echo __('<tr><td>1014-46</td><td>Some product plugin.</td><td>000111-0055369</td><td>www.google.ca/reg</td></tr>');
    echo __('<tr><td>1014-00</td><td>Another great plugin Ver1.</td><td>654-abc-456-777</td><td>www.mmstore.ca/activate</td></tr>');
    echo __('<tr><td>1014-46</td><td>Some product plugin.</td><td>000111-0055369</td><td>www.google.ca/reg</td></tr>');
    echo __('<tr><td>1014-00</td><td>Another great plugin Ver1.</td><td>654-abc-456-777</td><td>www.mmstore.ca/activate</td></tr>');
    echo __('<tr><td>1014-46</td><td>Some product plugin.</td><td>000111-0055369</td><td>www.google.ca/reg</td></tr>');
    echo __('<tr><td>1014-00</td><td>Another great plugin Ver1.</td><td>654-abc-456-777</td><td>www.mmstore.ca/activate</td></tr>');
    echo __('<tr><td>1014-46</td><td>Some product plugin.</td><td>000111-0055369</td><td>www.google.ca/reg</td></tr>');
    echo __('<tr><td>1014-00</td><td>Another great plugin Ver1.</td><td>654-abc-456-777</td><td>www.mmstore.ca/activate</td></tr>');
    echo __('<tr><td>1014-46</td><td>Some product plugin.</td><td>000111-0055369</td><td>www.google.ca/reg</td></tr>');
    echo __('<tr><td>1014-00</td><td>Another great plugin Ver1.</td><td>654-abc-456-777</td><td>www.mmstore.ca/activate</td></tr>');

    echo __('</table><br/><br/>');

?>
